### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Minshenyao** [xingliuchao/jd#1]
有没有挂在github或者云函数上运行的QQ阅读js脚本，这个抓cookie能不能出一份详细一点的教程，感谢大佬！

**Comment by xingliuchao** [comment]
APP还是小程序？

**Comment by Wangzaicattle** [comment]
> APP还是小程序？

小程序

**Comment by xingliuchao** [comment]
boxjs订阅，里面有详细教程。如果没显示出来，可能与你订阅的box相关的脚本冲突了。https://raw.githubusercontent.com/xingliuchao/jd/main/box.json
